### ISSUE TITLE
Can't connect to AWS Opensearch Service

### ISSUE THREAD

**Issue by logbasex** [AntonShuvaev/elasticsearch4idea#105]
Hi there,

I'm trying to connect AWS Opensearch Service following this [tutorial](https://www.intellij-elasticsearch.com/docs/features/connection/) and getting this error:

Connection test failed: java.net.UnknownHostException: 
`vpc-appName-prod-**************************.[ap-southeast-2.es.amazonaws.com](http://ap-southeast-2.es.amazonaws.com/)`

Is there any with to fix that?
Thanks.

**Comment by AntonShuvaev** [comment]
Hi,

Your issue might be due to your OpenSearch domain endpoint is in a VPC and therefore not reachable from the internet.
While I'm not an AWS expert, one possible solution is to use a "bastion host" in your VPC.
You will need to establish an SSH connection to this bastion host, which can be configured in the SSH tab of the connection settings. Once configured, you will be able to connect to the OpenSearch domain endpoint in your VPC.
