### ISSUE TITLE
can't download required driver for plugin: APACHE-LICENSE-2.0 Request failed with status code 404

### ISSUE THREAD

**Issue by pantafive** [AntonShuvaev/elasticsearch4idea#106]
Failed to download 'https://cache-redirector.jetbrains.com/download.jetbrains.com/idea/jdbc-drivers/APACHE-LICENSE-2.0':
Request failed with status code 404

![image](https://github.com/AntonShuvaev/elasticsearch4idea/assets/56078241/269a3552-c9f1-498b-9d55-11f9231fbb1d)

**Comment by AntonShuvaev** [comment]
Hi, this issue is not related to the Elasticsearch plugin. It appears you might have tried to create a connection using the Database plugin bundled with the IDE. It does have Elasticsearch functionality, but it's limited by the use of a JDBC driver. To create a connection in the Elasticsearch plugin, open the `Elasticsearch` tool window and click on the `Add connection` button.
