### ISSUE TITLE
Chinese symbols are not displayed in table view

### ISSUE THREAD

**Issue by yixiaco** [AntonShuvaev/elasticsearch4idea#5]
![image](https://user-images.githubusercontent.com/30982989/88354737-7cbf7f00-cd94-11ea-9419-e07faba2ad9d.png)
然而正常情况下，它应该是这样子的
![image](https://user-images.githubusercontent.com/30982989/88354768-9e206b00-cd94-11ea-8842-d29f01100396.png)

**Comment by AntonShuvaev** [comment]
Hello,

Is it the same document in the table and text views? I cannot reproduce the problem. But I found that if I post a document with Chinese symbols then they are stored incorrectly in Elasticsearch and I see question marks in both table and text views. This happens because request body is encoded with default ISO 8859-1 instead of UTF-8.

**Comment by yixiaco** [comment]
是的，只有带中文符号的字符会看到问号，图中的数据是第一条记录，然而它并没有正确显示

**Comment by yixiaco** [comment]
![image](https://user-images.githubusercontent.com/30982989/88368292-57486a80-cdc0-11ea-99ec-4b2f4b3d49b2.png)
![image](https://user-images.githubusercontent.com/30982989/88368307-5dd6e200-cdc0-11ea-9d26-9ee2ce0e5664.png)

**Comment by AntonShuvaev** [comment]
@18905059768 ,  

The fix is ready and will be in version 0.1.9. Let me know if it resolves your issue.

**Comment by yixiaco** [comment]
very good,该版本很好的解决了我的问题
