### ISSUE TITLE
Cannot browse past 10000th document

### ISSUE THREAD

**Issue by ostrolucky** [AntonShuvaev/elasticsearch4idea#53]
Related to https://github.com/AntonShuvaev/elasticsearch4idea/issues/49:

Originally, I demonstrated the case where I changed page size. However, looks like issue is there even with default page size, which is 10 results, once I go above result 10000.
![2021-11-03_19-09-12 (1)](https://user-images.githubusercontent.com/496233/140168013-3f2b209d-488b-4e91-88a1-773373670c59.gif)

**Comment by AntonShuvaev** [comment]
Thanks for the feature request.

The max result (10000) is limited by [index.max_result_window](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-max-result-window). As a workaround, it can be increased but this can affect the performance. 
Also, a workaround is to use [search_after](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after) manually adding to your request:
```
  "sort": [
    {
      "_doc": {
        "order": "asc"
      }
    }
  ],
  "search_after": [
    9999
  ]
  ```
  Of course, it is not very convenient to do it manually. 
  I will consider adding `search_after` automatically when the result is bigger than `index.max_result_window`. But this also has some disadvantages: in a common case, we don't know how many documents were before so we can't show the page number and we can go only forward. 

Usually, it is not necessary to get more than 10000 documents since you can specify filters and reduce the result. Could you describe your use case in more detail?
